# Generated by Django 5.1.7 on 2025-09-10 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_app', '0003_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=200)),
                ('picture', models.FileField(upload_to='products')),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(max_length=6)),
                ('status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_product', to='ec_app.seller')),
            ],
        ),
    ]
