# Generated by Django 5.1.7 on 2025-09-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_app', '0004_product_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_add',
            name='picture',
            field=models.FileField(upload_to='products/'),
        ),
    ]
